from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

app = Flask(__name__)
app.config.from_object(Config)
db = SQLAlchemy(app)
migrate = Migrate(app, db)

from app import routes, models

# c = models.Client(phone='89745612321',  passport='4568789456', name='IlyaGreen')
# c2 = models.Client(phone='89741234567',  passport='4589621234', name='KarolGreen')
# d = models.Delivery(client=c, user_code=123456)
# d2 = models.Delivery(client=c2, user_code=123457)
# d3 = models.Delivery(client=c2, user_code=123458)
# cell = models.Cell(capacity=3)
# cell1 = models.Cell(capacity=3)
# cell2 = models.Cell(capacity=3)
# cell3 = models.Cell(capacity=3)
# cell4 = models.Cell(capacity=3)
# cell5 = models.Cell(capacity=3)
# cell6 = models.Cell(capacity=3)
# it_cel = models.Items_cell(cell=cell)
# i = models.Item(barcode=12, delivery=d, cell=it_cel)
# it = models.Item(barcode=14, delivery=d)
# it1 = models.Item(barcode=15, delivery=d2)
# it2 = models.Item(barcode=16, delivery=d3)
# it3 = models.Item(barcode=17, delivery=d3)
# db.session.add(c)
# db.session.add(c2)
# db.session.add(d)
# db.session.add(d2)
# db.session.add(d3)
# db.session.add(cell)
# db.session.add(cell1)
# db.session.add(cell2)
# db.session.add(cell3)
# db.session.add(cell4)
# db.session.add(cell5)
# db.session.add(cell6)
# db.session.add(it_cel)
# db.session.add(i)
# db.session.add(it)
# db.session.add(it1)
# db.session.add(it2)
# db.session.add(it3)
# db.session.commit()

#cell = models.Cell(capacity=3)
# it = models.Item(barcode=21, delivery=models.Delivery.query.get(1))
# db.session.add(it)
# db.session.commit()